# Generated by Django 5.0.14 on 2025-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("Waiter", "Waiter"),
                    ("Chef", "Chef"),
                    ("Manager", "Manager"),
                ],
                max_length=50,
            ),
        ),
    ]
